# Generated by Django 4.2.6 on 2023-11-14 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество очков')),
                ('created', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Время создания записи')),
            ],
            options={
                'verbose_name': 'Запись об изменении очков у пользователя',
                'verbose_name_plural': 'Запись об изменении очков у пользователя',
            },
        ),
        migrations.CreateModel(
            name='PointCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Условие для изменения количества очков Score')),
            ],
            options={
                'verbose_name': 'Условие начисления очков Score',
                'verbose_name_plural': 'Условие начисления очков Score',
            },
        ),
    ]
