# Generated by Django 4.2.6 on 2023-11-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Score', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcondition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PointConditionUserID', to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='historypoint',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionID', to='Score.pointcondition', unique=True, verbose_name='condition_id'),
        ),
        migrations.AddField(
            model_name='historypoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HistoryPointUserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
