# Generated by Django 4.2.6 on 2023-11-02 02:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Score', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historypoint',
            options={'verbose_name': 'Запись об изменении очков у пользователя', 'verbose_name_plural': 'Запись об изменении очков у пользователя'},
        ),
        migrations.AlterModelOptions(
            name='pointcondition',
            options={'verbose_name': 'Условие начисления очков Score', 'verbose_name_plural': 'Условие начисления очков Score'},
        ),
        migrations.AlterField(
            model_name='historypoint',
            name='condition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='conditionID', to='Score.pointcondition', unique=True, verbose_name='condition_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historypoint',
            name='count',
            field=models.IntegerField(verbose_name='Количество очков'),
        ),
        migrations.AlterField(
            model_name='historypoint',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания записи'),
        ),
        migrations.AlterField(
            model_name='historypoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HistoryPointUserID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointcondition',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Условие для изменения количества очков Score'),
        ),
        migrations.AlterField(
            model_name='pointcondition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PointConditionUserID', to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
