# Generated by Django 4.2.6 on 2023-11-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0002_alter_historypoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypoint',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionID', to='Score.pointcondition', verbose_name='condition_id'),
        ),
    ]
