# Generated by Django 4.2.6 on 2023-11-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0003_alter_historypoint_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypoint',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditionID', to='Score.pointcondition', unique=True, verbose_name='condition_id'),
        ),
    ]
