# Generated by Django 4.2.6 on 2023-11-02 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0004_alter_historypoint_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historypoint',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Время создания записи'),
        ),
    ]
