# Generated by Django 4.2.5 on 2023-12-21 12:27

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image_url', models.FileField(upload_to='hackatons/')),
                ('description', models.TextField()),
                ('description_short', models.TextField()),
                ('creator', models.CharField(max_length=150)),
                ('start_registration', models.DateTimeField(default=datetime.datetime.now)),
                ('end_registration', models.DateTimeField()),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('end', models.DateTimeField()),
                ('grand_prize', models.CharField(blank=True, max_length=150)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hackaton_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('hackaton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hackaton')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('hackaton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton_user')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_invited', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton_user')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'accept'), ('pending', 'pending'), ('decline', 'decline')], default='pending', max_length=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackaton.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackaton.hackaton_user')),
            ],
        ),
        migrations.AddField(
            model_name='hackaton',
            name='tracks',
            field=models.ManyToManyField(to='Hackaton.track'),
        ),
    ]
