# Generated by Django 4.2.5 on 2023-11-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackaton',
            old_name='descriptionShort',
            new_name='description_short',
        ),
    ]
