# Generated by Django 4.2.5 on 2023-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackaton',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='Hackaton.track'),
        ),
    ]
