# Generated by Django 4.2.5 on 2023-10-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0002_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackaton.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hackaton.hackaton_user')),
            ],
        ),
    ]
