# Generated by Django 4.2.5 on 2023-12-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0002_alter_hackaton_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackaton',
            name='tracks',
        ),
        migrations.AddField(
            model_name='track',
            name='hackaton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hackaton.hackaton'),
            preserve_default=False,
        ),
    ]
