# Generated by Django 4.2.5 on 2023-12-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0003_remove_hackaton_tracks_track_hackaton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='hackaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Hackaton.hackaton'),
        ),
    ]
