# Generated by Django 4.2.5 on 2023-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hackaton', '0003_team_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_team',
            name='is_invited',
            field=models.BooleanField(default=True),
        ),
    ]
