# Generated by Django 4.2.5 on 2023-10-23 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hackaton', '0004_user_team_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackaton',
            name='descriptionShort',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackaton',
            name='grandPrize',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='hackaton',
            name='imageUrl',
            field=models.ImageField(default=1, upload_to='hackatons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackaton',
            name='isOnline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hackaton',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hackaton_user',
            name='hackaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton'),
        ),
        migrations.AlterField(
            model_name='hackaton_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='hackaton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton_user'),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.team'),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hackaton.hackaton_user'),
        ),
        migrations.DeleteModel(
            name='Team_Invite',
        ),
    ]
