# Generated by Django 4.2.5 on 2023-11-12 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hackaton', '0005_hackaton_descriptionshort_hackaton_grandprize_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hackaton_user',
            unique_together={('user', 'hackaton')},
        ),
    ]
