# Generated by Django 4.2.7 on 2023-11-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Тело контакта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('begin', models.DateTimeField(null=True, verbose_name='Начало образования')),
                ('end', models.DateTimeField(null=True, verbose_name='Окончание образования')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровень образования',
            },
        ),
        migrations.CreateModel(
            name='Hackatons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('begin', models.DateTimeField(null=True, verbose_name='Начало хакатона')),
                ('end', models.DateTimeField(null=True, verbose_name='Конец хакатона')),
                ('place', models.IntegerField(verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Хакатоны',
                'verbose_name_plural': 'Хакатоны',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('begin', models.DateTimeField(null=True, verbose_name='Начало')),
                ('end', models.DateTimeField(null=True, verbose_name='Конец')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Resume.resume')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работа',
            },
        ),
    ]
