# Generated by Django 4.2.7 on 2023-11-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='hackatons',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackatons', to='Resume.resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.graduation', verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaion', to='Resume.resume'),
        ),
        migrations.AddField(
            model_name='contact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Resume.resume'),
        ),
    ]
