# Generated by Django 4.2.6 on 2023-10-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.graduation'),
        ),
    ]
