# Generated by Django 4.2.6 on 2023-10-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Resume', '0004_alter_resume_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='graduation',
            options={'verbose_name': 'Уровень образования', 'verbose_name_plural': 'Уровень образования'},
        ),
        migrations.AlterModelOptions(
            name='hackatons',
            options={'verbose_name': 'Хакатоны', 'verbose_name_plural': 'Хакатоны'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работа'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(verbose_name='Тело контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Resume.resume', unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='education',
            name='begin',
            field=models.DateTimeField(null=True, verbose_name='Начало образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Окончание образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Resume.graduation', verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaion', to='Resume.resume', unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='graduation',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='begin',
            field=models.DateTimeField(null=True, verbose_name='Начало хакатона'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Конец хакатона'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='place',
            field=models.IntegerField(verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackatons', to='Resume.resume', unique=True),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='work',
            name='begin',
            field=models.DateTimeField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Resume.resume', unique=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
