# Generated by Django 4.2.6 on 2023-11-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_alter_contact_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Resume.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaion', to='Resume.resume'),
        ),
        migrations.AlterField(
            model_name='hackatons',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackatons', to='Resume.resume'),
        ),
        migrations.AlterField(
            model_name='work',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='Resume.resume'),
        ),
    ]
