# Generated by Django 4.2.6 on 2023-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0006_alter_contact_resume_alter_education_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Заголовок'),
        ),
    ]
