name: Deploy to VPS
run-name: Deploy changes by ${{ github.actor }} on prod

on:
  push:
    branches:
      - master
#      - CI_CD

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd HackatonService && git pull origin master && docker compose up --build -d
          
